# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test-pl.ui'
#
# Created: Wed Apr  4 22:26:29 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ProjetGherkin(object):
    def setupUi(self, ProjetGherkin):
        ProjetGherkin.setObjectName(_fromUtf8("ProjetGherkin"))
        ProjetGherkin.resize(825, 778)
        ProjetGherkin.setWindowTitle(QtGui.QApplication.translate("ProjetGherkin", "Projet Gherkin", None, QtGui.QApplication.UnicodeUTF8))
        ProjetGherkin.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(ProjetGherkin)
        self.centralwidget.setAcceptDrops(False)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.SongBar = QtGui.QSlider(self.centralwidget)
        self.SongBar.setOrientation(QtCore.Qt.Horizontal)
        self.SongBar.setObjectName(_fromUtf8("SongBar"))
        self.gridLayout.addWidget(self.SongBar, 0, 0, 1, 2)
        self.LookingFor = QtGui.QLineEdit(self.centralwidget)
        self.LookingFor.setText(_fromUtf8(""))
        self.LookingFor.setReadOnly(False)
        self.LookingFor.setObjectName(_fromUtf8("LookingFor"))
        self.gridLayout.addWidget(self.LookingFor, 1, 1, 1, 1)
        self.RandomButton = QtGui.QPushButton(self.centralwidget)
        self.RandomButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../.designer/backup/Random.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RandomButton.setIcon(icon)
        self.RandomButton.setIconSize(QtCore.QSize(30, 30))
        self.RandomButton.setFlat(True)
        self.RandomButton.setObjectName(_fromUtf8("RandomButton"))
        self.RandomRepeat = QtGui.QButtonGroup(ProjetGherkin)
        self.RandomRepeat.setObjectName(_fromUtf8("RandomRepeat"))
        self.RandomRepeat.addButton(self.RandomButton)
        self.gridLayout.addWidget(self.RandomButton, 1, 3, 1, 1)
        self.Album = QtGui.QTreeWidget(self.centralwidget)
        self.Album.setObjectName(_fromUtf8("Album"))
        self.Album.headerItem().setText(0, QtGui.QApplication.translate("ProjetGherkin", "Album", None, QtGui.QApplication.UnicodeUTF8))
        self.Album.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item_0 = QtGui.QTreeWidgetItem(self.Album)
        self.Album.topLevelItem(0).setText(0, QtGui.QApplication.translate("ProjetGherkin", "Banane", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.Album, 3, 0, 6, 1)
        self.Artiste = QtGui.QTreeWidget(self.centralwidget)
        self.Artiste.setObjectName(_fromUtf8("Artiste"))
        self.Artiste.headerItem().setText(0, QtGui.QApplication.translate("ProjetGherkin", "Artiste", None, QtGui.QApplication.UnicodeUTF8))
        self.Artiste.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item_0 = QtGui.QTreeWidgetItem(self.Artiste)
        self.Artiste.topLevelItem(0).setText(0, QtGui.QApplication.translate("ProjetGherkin", "Mangue", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.Artiste)
        self.Artiste.topLevelItem(1).setText(0, QtGui.QApplication.translate("ProjetGherkin", "Kiwi", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.Artiste)
        self.Artiste.topLevelItem(2).setText(0, QtGui.QApplication.translate("ProjetGherkin", "Asperge", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.Artiste)
        self.Artiste.topLevelItem(3).setText(0, QtGui.QApplication.translate("ProjetGherkin", "Goyave", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.Artiste, 3, 1, 6, 1)
        self.RepeatButton = QtGui.QPushButton(self.centralwidget)
        self.RepeatButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../.designer/backup/Repeat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RepeatButton.setIcon(icon1)
        self.RepeatButton.setIconSize(QtCore.QSize(30, 30))
        self.RepeatButton.setFlat(True)
        self.RepeatButton.setObjectName(_fromUtf8("RepeatButton"))
        self.RandomRepeat.addButton(self.RepeatButton)
        self.gridLayout.addWidget(self.RepeatButton, 3, 3, 1, 1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 5, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 3, 1, 1)
        self.PreviousButton = QtGui.QPushButton(self.centralwidget)
        self.PreviousButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../.designer/backup/backward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PreviousButton.setIcon(icon2)
        self.PreviousButton.setIconSize(QtCore.QSize(30, 30))
        self.PreviousButton.setFlat(True)
        self.PreviousButton.setObjectName(_fromUtf8("PreviousButton"))
        self.PlayPN = QtGui.QButtonGroup(ProjetGherkin)
        self.PlayPN.setObjectName(_fromUtf8("PlayPN"))
        self.PlayPN.addButton(self.PreviousButton)
        self.gridLayout.addWidget(self.PreviousButton, 7, 3, 1, 1)
        self.PisteAudio = QtGui.QTreeWidget(self.centralwidget)
        self.PisteAudio.setObjectName(_fromUtf8("PisteAudio"))
        self.PisteAudio.headerItem().setText(0, QtGui.QApplication.translate("ProjetGherkin", "Piste audio", None, QtGui.QApplication.UnicodeUTF8))
        self.PisteAudio.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item_0 = QtGui.QTreeWidgetItem(self.PisteAudio)
        self.PisteAudio.topLevelItem(0).setText(0, QtGui.QApplication.translate("ProjetGherkin", "Boris Elsin", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.PisteAudio)
        self.PisteAudio.topLevelItem(1).setText(0, QtGui.QApplication.translate("ProjetGherkin", "Plop", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.PisteAudio, 9, 0, 4, 2)
        self.NextButton = QtGui.QPushButton(self.centralwidget)
        self.NextButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../.designer/backup/forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextButton.setIcon(icon3)
        self.NextButton.setIconSize(QtCore.QSize(30, 30))
        self.NextButton.setAutoDefault(False)
        self.NextButton.setDefault(False)
        self.NextButton.setFlat(True)
        self.NextButton.setObjectName(_fromUtf8("NextButton"))
        self.PlayPN.addButton(self.NextButton)
        self.gridLayout.addWidget(self.NextButton, 10, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 11, 3, 1, 1)
        self.verticalSlider = QtGui.QSlider(self.centralwidget)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.gridLayout.addWidget(self.verticalSlider, 12, 3, 1, 1)
        self.PlayButton = QtGui.QPushButton(self.centralwidget)
        self.PlayButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../.designer/backup/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PlayButton.setIcon(icon4)
        self.PlayButton.setIconSize(QtCore.QSize(30, 30))
        self.PlayButton.setFlat(True)
        self.PlayButton.setObjectName(_fromUtf8("PlayButton"))
        self.PlayPN.addButton(self.PlayButton)
        self.gridLayout.addWidget(self.PlayButton, 9, 3, 1, 1)
        self.commandLinkButton = QtGui.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setText(QtGui.QApplication.translate("ProjetGherkin", "CommandLinkButton", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.gridLayout.addWidget(self.commandLinkButton, 1, 0, 1, 1)
        ProjetGherkin.setCentralWidget(self.centralwidget)
        self.MenuBarPG = QtGui.QMenuBar(ProjetGherkin)
        self.MenuBarPG.setGeometry(QtCore.QRect(0, 0, 825, 25))
        self.MenuBarPG.setFocusPolicy(QtCore.Qt.NoFocus)
        self.MenuBarPG.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.MenuBarPG.setAutoFillBackground(False)
        self.MenuBarPG.setDefaultUp(False)
        self.MenuBarPG.setNativeMenuBar(False)
        self.MenuBarPG.setObjectName(_fromUtf8("MenuBarPG"))
        self.menuMedia = QtGui.QMenu(self.MenuBarPG)
        self.menuMedia.setTitle(QtGui.QApplication.translate("ProjetGherkin", "Media", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMedia.setObjectName(_fromUtf8("menuMedia"))
        self.menuAffichage = QtGui.QMenu(self.MenuBarPG)
        self.menuAffichage.setTitle(QtGui.QApplication.translate("ProjetGherkin", "Affichage", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAffichage.setObjectName(_fromUtf8("menuAffichage"))
        self.menuEdition = QtGui.QMenu(self.MenuBarPG)
        self.menuEdition.setTitle(QtGui.QApplication.translate("ProjetGherkin", "Edition", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdition.setObjectName(_fromUtf8("menuEdition"))
        ProjetGherkin.setMenuBar(self.MenuBarPG)
        self.statusbar = QtGui.QStatusBar(ProjetGherkin)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ProjetGherkin.setStatusBar(self.statusbar)
        self.actionImporter_Dossier = QtGui.QAction(ProjetGherkin)
        self.actionImporter_Dossier.setText(QtGui.QApplication.translate("ProjetGherkin", "Importer Dossier", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImporter_Dossier.setObjectName(_fromUtf8("actionImporter_Dossier"))
        self.actionImporter_Fichier = QtGui.QAction(ProjetGherkin)
        self.actionImporter_Fichier.setText(QtGui.QApplication.translate("ProjetGherkin", "Importer Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImporter_Fichier.setObjectName(_fromUtf8("actionImporter_Fichier"))
        self.actionPr_f_rence = QtGui.QAction(ProjetGherkin)
        self.actionPr_f_rence.setText(QtGui.QApplication.translate("ProjetGherkin", "Préférence", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPr_f_rence.setObjectName(_fromUtf8("actionPr_f_rence"))
        self.menuMedia.addAction(self.actionImporter_Dossier)
        self.menuMedia.addAction(self.actionImporter_Fichier)
        self.menuEdition.addAction(self.actionPr_f_rence)
        self.MenuBarPG.addAction(self.menuMedia.menuAction())
        self.MenuBarPG.addAction(self.menuAffichage.menuAction())
        self.MenuBarPG.addAction(self.menuEdition.menuAction())

        self.retranslateUi(ProjetGherkin)
        QtCore.QObject.connect(self.LookingFor, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.Album.close)
        QtCore.QObject.connect(self.PlayButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.PisteAudio.clear)
        QtCore.QObject.connect(self.Album, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QTreeWidgetItem*,int)")), self.Artiste.selectAll)
        QtCore.QMetaObject.connectSlotsByName(ProjetGherkin)

    def retranslateUi(self, ProjetGherkin):
        __sortingEnabled = self.Album.isSortingEnabled()
        self.Album.setSortingEnabled(False)
        self.Album.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.Artiste.isSortingEnabled()
        self.Artiste.setSortingEnabled(False)
        self.Artiste.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.PisteAudio.isSortingEnabled()
        self.PisteAudio.setSortingEnabled(False)
        self.PisteAudio.setSortingEnabled(__sortingEnabled)

